version: '2'

services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal-module:/var/www/html/module
      - drupal-profile:/var/www/html/profile
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword

volumes:
  drupal-module:
  drupal-profile:
  drupal-sites:
  drupal-themes:
  
